### PR TITLE
12/bonds

### PR DESCRIPTION
**Pull request by hagoptaminian**
@pyphilia @juancarlosfarah please let me know if you have any feedback before we deploy this. Overall, the application status is:

- Since last PR, I added (1) radiation line absorption by greenhouse gases, (2) bonds between atoms
- The methane molecule still doesn't have bonds added (it's a bit complicated - I will do this, but thought it's worth getting teacher feedback first anyway)
- If all is OK, the next step would be to oscillate greenhouse gas atoms

### CODE REVIEW

**Comment by pyphilia** [comment]
That's really smart how you did the bonds! I like it.  Some random points:
- Why didn't you use the same PR? I think it would have been okay to update the previous one, as it would have kept my review's state.
- Did you have a look to state machines? Could it fit the project or was it too complex? 
- The only one comment I have is that I would go with bolder bonds, with `strokeWidth={3}` at least and darkgrey I think.

Good work!

**Comment by hagoptaminian** [comment]
Thanks @pyphilia :)

- For a new, separate PR for the last two commits: Let's see how/if we rebase after @juancarlosfarah reviews
- Still haven't looked at state machines, but I will
- I'm assuming you mean for the Canvas bonds? I am open to changing their styling. Let's see what the teachers say as well.

**Comment by juancarlosfarah** [comment]
@hagoptaminian, could you do a quick rebase so that we can merge this one too?

**Comment by hagoptaminian** [comment]
@juancarlosfarah done!

**Pull request merged**
